---
# tasks file for myapache
#
- name: "Installing Apache Software"
  dnf:
    name: "{{ software_name }}"
    state: present

- name: "Copying Webpages.."
  copy:
     src: "/etc/ansible/roles/myapache/files/index.html"
     dest: "/var/www/html/"
  notify: "Restart Services"

- name: "Starting Service"
  service:
     name: "{{ software_name }}"
     state: started
