---
# tasks file for myloadbalancer
#
- name: "Installing Apache Software"
  dnf:
    name: "{{ software_name }}"
    state: present

- name: "Configuration File"
  template:
     src: "/etc/ansible/roles/myloadbalancer/templates/haproxy.cfg.j2"
     dest: "/etc/haproxy/haproxy.cfg"
  notify: "Restart Services"

- name: "Starting Services"
  service:
      name: "{{ software_name }}"
      state: started
